"use client";

import BrandedProductPage, { BrandDef, ProductDef } from '../shared/BrandedProductPage';

const category = {
	"id": "surgical-rehabilation",
	"title": "Medical Surgical and Rehab Ward",
	"description": "Hospital beds, trolleys, and ward furniture for medical surgical and rehabilitation care"
};

// Brand sub-tabs — logo files live in /public/asset/logo
const brands: BrandDef[] = [
	{ id: "saikang", name: "Saikang", logo: "/asset/logo/saikang_logo.png" },
];

const products: ProductDef[] = [
	{"id":1,"name":"SKR-MT625 Medical Trolley","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/SKR-MT625.png","description":"This medical trolley features a heavy-duty, powder-coated frame with stable construction and four 100 mm nylon castors (two with brakes) for smooth, secure mobility. It includes multiple drawers with ABS dividers and a central lock, stainless steel side rails on the tabletop, dual color-coded ABS trash bins, and a side-attached file box, providing organized and safe storage for medicines, medical materials, and paperwork.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":2,"name":"SKR054-ET Emergency Trolley","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/SKR054-ET.png","description":"This medical trolley features a one-piece countertop with fully guarded and raised handles for safe and comfortable operation, along with a beveled decorative grip for better ergonomics. It offers deep, spacious drawers, a movable power socket above the CPR board, retractable oxygen bottle holder, IV pole, defibrillator placement, and color-coded trash bins, all built on a heavy-duty, stable frame with aligned wheels for secure mobility.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":3,"name":"SKS02-W Examination Table","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/SKS02-W.png","description":"This medical trolley is made from 100% pure ABS plastic, ensuring a non-toxic, durable, rust- and corrosion-resistant design that is easy to clean and long-lasting. It features a sunken ABS top to prevent items from falling, a hidden towel hook, stable casters (two with brakes), and a spacious cabinet with a shelf and drawer, available in customizable colors.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":4,"name":"SKB041-3 Patient Bed","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/SKB041-3.png","description":"This hospital stretcher features a durable Baosteel frame with robotic 360° welding, 11-step epoxy painting, and antibacterial testing, ensuring strength and impact resistance. It includes dual US hydraulic pumps for height and Trendelenburg adjustments, foldable aluminum side rails, waterproof PU mattress, 8″ double casters with brakes and center wheel for easy maneuvering, detachable bumper wheels, IV pole, and mobile drainage hooks, all designed for safe, efficient patient transport and care.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":5,"name":"SKB041-1 Patient Stretcher","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/SKB041-1.png","description":"This hospital stretcher features a robust Baosteel frame with robotic 360° welding, epoxy-painted bed frame and chassis, and high-quality PP bed platform and guardrails for durability and hygiene. It includes a backrest lift up to 70°, four 6-inch double-sided castors with locks, a directional center wheel, telescopic IV poles, oxygen bottle holders, stainless steel handles, safety straps, and a 2 cm thick standard mattress for safe and comfortable patient transport.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":6,"name":"K3K Hospital Bed","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/K3k.png","description":"SAIKANG ensures high-quality medical furniture through strict selection of branded materials, robotic welding, automated epoxy coating, and rigorous quality control. Its modern, practical design features elegant head and footboards, durable sterilizable plastics, and robust epoxy-painted steel capable of withstanding impacts up to 50 kg.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":7,"name":"Manual 2 Cranks Bed","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/MANUAL%202%20CRANKS%20BED.png","description":"The Saikang K2K is a durable, manual 2-crank hospital bed known for its basic functions: backrest and knee rest adjustments, controlled by two separate hand cranks, often with aluminum alloy side rails, steel frame, and options like IV poles, offering reliable patient positioning for hospitals and home care at an economical price point. Key features include robust construction with robot-welded surfaces, mattress retainers, and drainage hooks, with cranks designed for longevity. ","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":8,"name":"Electric 3 Function Bed","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/ELECTRIC%203%20FUNCTION%20BED.png","description":"The Saikang V6K is a budget-friendly, customizable electric 3-function hospital/homecare bed, allowing motorized adjustments for backrest, leg rest, and overall height/tilt, featuring durable ABS materials, aluminum alloy guardrails, and robust motors for patient comfort and nurse assistance in positioning and transfers. Key features include optional dining tables, drainage hooks, a one-button reset, and strong build quality from materials like Baosteel, making it suitable for home or clinical settings. ","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":9,"name":"Electric 5 Function Bed","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/ELECTRIC%205%20FUNCTION%20BED.png","description":"The Saikang V6v is a versatile, electric 5-function hospital bed designed for patient comfort and care, offering adjustments for backrest, leg rest, height, and Trendelenburg/reverse Trendelenburg, controlled by a user-friendly backlit handset, featuring durable materials, integrated side rails, and bumpers for safety in clinical settings. ","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":10,"name":"Electric 5 Function Orthopedic Bed","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/ELECTRIC%205%20FUNCTION%20ORTHOPEDIC%20BED.png","description":"The Saikang GB8e is a 5-function electric orthopedic bed with height adjustment, backrest (0-75°), knee rest (0-35°), Trendelenburg (0-12°), and Reverse Trendelenburg (0-12°) functions, featuring a 250kg capacity, CPR function, durable steel/ABS build, central locking, and an aluminum traction frame for patient positioning. ","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":11,"name":"Manual Orthopedic Bed","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/MANUAL%20ORTHOPEDIC%20BED.png","description":"The Saikang B4w (or B4W) is a 4-crank, 5-function manual medical bed designed for ICU and general ward use, featuring a sturdy metal construction with a high weight capacity. It is designed for durability and patient comfort, with adjustable positions for backrest, legrest, height, Trendelenburg, and reverse Trendelenburg. ","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":12,"name":"SKE087 Reclining Chair","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/SKE087.png","description":"The SKE087 features a sectional backrest for strong spinal support, solid wood armrests, and a convenient cup holder, providing comfort and practicality for patients. It includes a one-touch reclining function, super-strong PU leather upholstery with flame-retardant high-density foam, a solid wood rotary table, and 3″ silent medical castors that are waterproof, anti-static, and antibacterial.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":13,"name":"SKE031 Medical Equipment Cart","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/SKE031.png","description":"This medical chair features a high-quality aluminum frame with a foldable footrest and adjustable height for patient comfort. It includes 3″ silent castors with dual brakes and a seat upholstered in PVC leather with high-density foam and wood for durability and support.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":14,"name":"SKE020-1D Medical Cabinet","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/SKE020-1D.png","description":"The SKE020-1D is a hospital bed foot step with a stainless steel frame and rubber anti-slip surface for safety. It features a single-step design and measures 410 × 230 × 220 mm, providing stable and convenient access for patients.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":15,"name":"SKH041 IV Pole","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/SKH041(1).png","description":"This stainless steel IV pole features a height-adjustable range of 1350–2250 mm and is constructed with durable inner (Φ16 mm) and outer (Φ25 mm) stainless steel tubes. It includes two stainless steel hooks, five five-pointed star plastic casters (2-inch double-sided, without brakes), and a stable base with a diameter of 520 mm.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":16,"name":"SKH042 Overbed Table","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/surgical-rehabilatation/SKH042.png","description":"This movable hospital table features a multi-layer solid wood tabletop with PVC edge banding (800 × 400 mm) and a height-adjustable gas spring system for easy operation. Its metal base with spray-coated stainless steel columns, four durable 2-inch rubber castors (two with brakes), and stable center of gravity make it suitable as a bedside or dining table for hospital use.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
];

export default function SurgicalRehabilitation() {
	return <BrandedProductPage category={category} brands={brands} products={products} ctaNoun="medical surgical and rehab ward" />;
}
