"use client";

import BrandedProductPage, { BrandDef, ProductDef } from '../shared/BrandedProductPage';

const category = {
	"id": "emergency-outpatient",
	"title": "Emergency and Out Patient",
	"description": "Comprehensive emergency and outpatient equipment including patient monitors, defibrillators, and examination tables"
};

// Brand sub-tabs — logo files live in /public/asset/logo
const brands: BrandDef[] = [
	{ id: "edan", name: "EDAN", logo: "/asset/logo/EDAN.png" },
	{ id: "comen", name: "Comen", logo: "/asset/logo/comen.png" },
	{ id: "byond", name: "Byond", logo: "/asset/logo/byond.png" },
	{ id: "uzumcu", name: "Uzumcu", logo: "/asset/logo/uzumcu.png" },
	{ id: "saikang", name: "Saikang", logo: "/asset/logo/saikang_logo.png" },
];

const products: ProductDef[] = [
	{"id":1,"name":"CX15 Patient Monitor","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/CX15%20Patient%20Monitor.png","description":"The CX15 patient monitor is designed for easy, reliable, and affordable patient monitoring, combining Edan’s 20 years of expertise with accurate performance and user-friendly operation. Featuring a 15.6” full HD display, portable design, long battery life, wide viewing angle, and 5G Wi-Fi connectivity, it supports gesture operation and HDMI output. Advanced algorithms ensure precise ECG, SpO₂, NIBP, and CO₂ monitoring with fast measurement, low false alarms, and strong motion resistance—making CX15 a practical and dependable solution for everyday clinical needs.","brand":"edan","brandName":"EDAN","brandLogo":"/asset/logo/EDAN.png"},
	{"id":2,"name":"iM3 Vital Signs Monitor","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/iM3%20Vital%20Signs%20Monitor.png","description":"The iM3 combines a sleek, ultra-slim design with an 8” capacitive touch screen to provide comprehensive vital signs monitoring, including SpO₂, NIBP, and Quick/Infrared Ear or Forehead Temperature. Lightweight (<2.5 kg) and equipped with barcode scanning, built-in memory, thermal printer, and adaptive work modes (Spot, Round, Monitoring), it supports both long-term patient monitoring and spot-check applications with real-time data, alarms, and trend analysis.","brand":"edan","brandName":"EDAN","brandLogo":"/asset/logo/EDAN.png"},
	{"id":3,"name":"X12 Patient Monitor","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/X12%20Patient%20Monitor.png","description":"The X12 patient monitor features a 12.1” ultra-slim display and supports monitoring for all patient types, from neonates to adults, in settings such as emergency rooms, general wards, cardiac units, and during in-hospital transfers. It provides standard parameters including 3/5-lead ECG, RESP, SpO₂, NIBP, and 2-channel TEMP, with optional 12-lead ECG, IBP, C.O., and EDAN G2 CO₂, all enhanced by proprietary algorithms for accurate arrhythmia detection, motion-resistant SpO₂ readings, precise NIBP, and intelligent CO₂ monitoring.","brand":"edan","brandName":"EDAN","brandLogo":"/asset/logo/EDAN.png"},
	{"id":4,"name":"H10 Finger Oximeter","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/H10%20Finger%20Oximeter.png","description":"The H10 finger oximeter features EDAN’s iMAT™ algorithm to deliver accurate SpO₂, pulse rate, and perfusion index readings for spot checks, triage, and homecare use. With a color OLED display, multiple viewing modes, adjustable brightness, long battery life, and IP22 protection, it is portable, reliable, and easy to operate.","brand":"edan","brandName":"EDAN","brandLogo":"/asset/logo/EDAN.png"},
	{"id":5,"name":"H100B Pulse Oximeter","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/H100B%20Pulse%20Oximeter.png","description":"The H100B handheld pulse oximeter provides reliable and accurate SpO₂ and pulse rate measurements for spot checks, even in challenging conditions. It features a backlit LCD with plethysmogram display, trend review, large data storage up to 300 hours, and PC data management for efficient patient monitoring","brand":"edan","brandName":"EDAN","brandLogo":"/asset/logo/EDAN.png"},
	{"id":6,"name":"PA-2S Portable Aspirator","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/PA-2S.png","description":"The UZUMCU portable aspirator is a battery-powered, lightweight device for minor surgical and bedside fluid removal. It delivers up to 620 mm Hg vacuum with 30 L/min flow, operates quietly (45 dBA), and features a 2 L transparent jar, hydrophobic filters, and an oil-free pump for easy cleaning and maintenance. CE-certified and suitable for OR, ICU, emergency, and dental use, it runs up to 30 minutes per charge. Made of durable ABS plastic, it includes all standard hoses and accessories. Dimensions: 230×420×360 mm; Weight: 4.132 kg (with battery).","brand":"uzumcu","brandName":"Uzumcu","brandLogo":"/asset/logo/uzumcu.png"},
	{"id":7,"name":"SD3 Ultrasonic Pocket Doppler","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/SD3%20Ultrasonic%20Pocket%20Doppler.png","description":"With excellent sensitivity, complete interchangeability and high durability, SD3 series Ultrasonic Pocket Dopplers are ideal for routine fetal heart rate detection by clinicians.","brand":"edan","brandName":"EDAN","brandLogo":"/asset/logo/EDAN.png"},
	{"id":8,"name":"Hopefusion Series Infusion Pump","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/Hopefusion%20Series%20Infusion%20Pump.png","description":"This infusion pump delivers high-precision, long-duration infusion with dual bubble detection, dynamic pressure monitoring, IP44 protection, and integrated power management for safe and reliable operation. It supports intelligent networking with Wi-Fi/wired connectivity, centralized monitoring, multi-channel configurations, multiple infusion modes (including TIVA), and a user-friendly touchscreen interface to streamline clinical workflows and enhance patient safety.","brand":"byond","brandName":"Byond","brandLogo":"/asset/logo/byond.png"},
	{"id":9,"name":"Hopefusion Series Syringe Pump","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/Hopefusion%20series%20Syringe%20Pump.png","description":"The Hopefusion Syringe Pump delivers high infusion accuracy (≤ ±1.8% after calibration) with dynamic pressure monitoring, dual control via a 3.5″ color touchscreen and keypad, and IP44 dust- and waterproof protection for safe clinical use. It supports intelligent networking with centralized monitoring, multi-channel power integration, multiple injection modes (including TIVA), and flexible syringe compatibility, helping simplify workflows while ensuring precise and reliable patient care.","brand":"byond","brandName":"Byond","brandLogo":"/asset/logo/byond.png"},
	{"id":10,"name":"F2F2A Automated External Defibrillator (AED)","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/Automated%20External%20Defibrillator%20F2F2A.png","description":"The F2/F2A AED is designed to improve survival in sudden cardiac arrest by providing fast, guided defibrillation and CPR assistance through clear voice prompts, animations, and pre-connected electrodes for adults and children. With automatic power-on when the lid is opened, one-button patient and language switching, and real-time CPR guidance, it delivers comprehensive, time-saving rescue support for both trained and untrained responders.","brand":"comen","brandName":"Comen","brandLogo":"/asset/logo/comen.png"},
	{"id":11,"name":"S8 Defibrillator Monitor","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/S8%20Defibrillator%20Monitor.png","description":"This defibrillator monitor supports manual defibrillation with synchronous cardioversion and asynchronous defibrillation, along with non-invasive pacing modes for effective management of cardiac arrest and severe bradyarrhythmias. It also provides comprehensive patient monitoring with standard 5-lead ECG, optional vital sign modules, and AED functionality with patented analysis algorithms to guide emergency responders during resuscitation.","brand":"comen","brandName":"Comen","brandLogo":"/asset/logo/comen.png"},
	{"id":12,"name":"S5 Defibrillator Monitor","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/S5%20Defibrillator%20Monitor.png","description":"This device supports manual defibrillation with synchronous cardioversion and asynchronous defibrillation, as well as on-demand and fixed non-invasive pacing for effective treatment of cardiac arrest and severe bradyarrhythmias. It features standard 5-lead ECG monitoring, optional vital sign modules including SpO₂, NIBP, PR, and EtCO₂, and an AED mode with patented automated analysis to guide emergency personnel in defibrillation and basic life support.","brand":"comen","brandName":"Comen","brandLogo":"/asset/logo/comen.png"},
	{"id":13,"name":"C6 HDC6A HD Video Colposcope","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/C6%20HDC6A%20HD%20Video%20Colposcope.png","description":"The C6 HD/C6A HD Video Colposcope combines a high-definition camera, advanced software, and a convenient workstation to meet the demanding needs of gynecological screening. It delivers superior image quality with over 900 TVL resolution, HD illumination, and adjustable LED lighting to clearly visualize examination areas. The green light mode enhances tissue contrast and highlights abnormal blood vessels for more accurate diagnosis. With flexible magnification, wide viewing angles, patient management software, and support for USB, SD, HDMI, and printing, this system enables easy, standardized, and efficient clinical use as well as teaching and case discussions.","brand":"edan","brandName":"EDAN","brandLogo":"/asset/logo/EDAN.png"},
	{"id":14,"name":"UHD Series Video Colposcope","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/UHD%20Series%20Video%20Colposcope.png","description":"UHD Series Video Colposcope has 8-megapixel resolution (3840×2160), delivering ultra-high-definition imaging that clearly reveals tiny lesions, vascular morphology, and subtle changes during acetic acid testing. Combined with BT.2020 wide color gamut, medical-grade 4K display, and multispectral light source imaging using white and narrow-band blue/green light, it provides true-to-life color reproduction, enhanced vessel contrast, and precise lesion boundary identification for more accurate clinical assessment.","brand":"edan","brandName":"EDAN","brandLogo":"/asset/logo/EDAN.png"},
	{"id":15,"name":"X09 Examination Table","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/X09%20Examination%20table.png","description":"The X09 features a backrest adjustable from 0–65° (±10°) and supports up to 175 kg. It has a durable 1.2–1.5 mm powder-coated steel frame, 4 anti-slip feet, and high-density 6 cm flame-retardant foam with 30 kg/m³ density. Upholstery is flame retardant, mildew-resistant, and wear-resistant (100,000 cycles). Constructed with Baosteel and precision robotic welding, it includes 11-layer epoxy painting (0.12 mm, 60° brightness) resistant to 50 kg impacts. External dimensions: 1900×600×680 mm.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":16,"name":"A048 Gynecological Examination Table","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/A048%20GynecoloGical%20examination%20table.png","description":"The A048 examination table features a mechanically adjustable back plate (0–75° ±10°) and a retractable foot board for patient comfort and space efficiency. It includes an integrated pillow, hidden basin, lithotomy rod (adjustable in height and angle), paper roll holder, and large drawers for tool storage. Built with a 0.8 mm thick base cabinet, the table supports up to 250 kg, and also offers a retractable auxiliary leg section and step stool. Additional features include a stainless steel basin and a power outlet for convenient clinical use.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":17,"name":"SKB041-10 Patient Transportation Trolley","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/SKB041-10.png","description":"The SKB041-10 features fixable side-rails that can be positioned horizontally to support IV administration or other treatments, with an innovative design allowing zero-gap patient transfer from stretcher to bed. It includes a degree indicator on the guardrail, a T-shaped gap for tubing, a full stainless-steel IV pole (15 kg capacity), waterproof mattress, foldable handle, bumpers at all four corners, 8″ central castors, and a center wheel for easy directional control. Height adjustment and Trendelenburg/reverse Trendelenburg functions are supported by a high-quality American hydraulic pump.","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":18,"name":"Spine Board","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/SPINE%20BOARD.png","description":"This product is blow molded by high density plastic polyethylene, strong and durable, not easy to aging","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":19,"name":"Ambulance Stretcher","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/AMBULANCE%20STRETCHER.png","description":"The Saikang SKB039(D) Ambulance Stretcher Trolley is a 2-section, foldable, and height-adjustable patient transport device designed for ambulances, hospitals, and emergency rescue situations. It features a lightweight, high-strength aluminum alloy structure. ","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
	{"id":20,"name":"Ambulance Chair Stretcher","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/emergency-outpatient/AMBULANCE%20CHAIR%20STRETCHER.png","description":"The Saikang SKB039(F) Aluminum Ambulance Chair Stretcher is a versatile, foldable patient transport trolley designed for ambulances and emergency,, frequently used in hospitals and for rescue operations. It is engineered to quickly convert from a horizontal stretcher into a seated chair, with features designed for ease of use in narrow spaces. ","brand":"saikang","brandName":"Saikang","brandLogo":"/asset/logo/saikang_logo.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px] sm:max-w-[110px]"},
];

export default function EmergencyOutpatient() {
	return <BrandedProductPage category={category} brands={brands} products={products} ctaNoun="emergency and outpatient" />;
}
