"use client";

import BrandedProductPage, { BrandDef, ProductDef } from '../shared/BrandedProductPage';

const category = {
	"id": "chemicals-consumables",
	"title": "Histopathology Chemicals & Consumables",
	"description": "Reagents, stains, solvents, and histopathology consumables"
};

// Brand sub-tabs — logo files live in /public/asset/logo
const brands: BrandDef[] = [
	{ id: "eam", name: "EAM", logo: "/asset/logo/EAM.png" },
	{ id: "dakewe", name: "Dakewe", logo: "/asset/logo/DAKEWE.png" },
	{ id: "citotest", name: "Citotest", logo: "/asset/logo/citotest.png" },
];

const products: ProductDef[] = [
	{"id":1,"name":"Paraffin Wax","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/Paraffin%20Wax.png","description":"Designed for improved tissue section infiltration & embedding and supplied in convenient pearl shape","brand":"citotest","brandName":"Citotest","brandLogo":"/asset/logo/citotest.png"},
	{"id":2,"name":"Histoflo™ Embedding Cassettes","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/Histoflo%E2%84%A2%20Embedding%20Cassettes.png","description":"Safe specimen, effective processing, smooth sectioning","brand":"dakewe","brandName":"Dakewe","brandLogo":"/asset/logo/DAKEWE.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px]"},
	{"id":3,"name":"Histoflo™ Microscope Slides","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/Histoflo%E2%84%A2%20Microscope%20Slides.png","description":"Great laser print outcome and long-term storage","brand":"dakewe","brandName":"Dakewe","brandLogo":"/asset/logo/DAKEWE.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px]"},
	{"id":4,"name":"Histoflo™ Adhesion Microscope Slides","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/Histoflo%E2%84%A2%20Adhesion%20Microscope%20Slides.png","description":"Special coating to improve tissue adherence","brand":"dakewe","brandName":"Dakewe","brandLogo":"/asset/logo/DAKEWE.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px]"},
	{"id":5,"name":"Histoflo™ Etching Microscope Slides","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/Histoflo%E2%84%A2%20Etching%20Microscope%20Slides.png","description":"Enhanced, extra dark printing outcome","brand":"dakewe","brandName":"Dakewe","brandLogo":"/asset/logo/DAKEWE.png","brandLogoClass":"h-[22px] sm:h-[26px] max-w-[100px]"},
	{"id":6,"name":"Reagent Alcohol","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/transparent/reagent-alcohol.webp","description":"Reagent Alcohol is a balanced blend of ethanol, methanol, and isopropanol designed for efficient and gradual tissue dehydration. This combination ensures consistent water removal while minimizing tissue distortion and preserving cellular morphology.","brand":"eam","brandName":"EAM","brandLogo":"/asset/logo/EAM.png"},
	{"id":7,"name":"Absolute Ethanol & Denatured Ethanol","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/transparent/absolute-ethanol-denatured-ethanol.webp","description":"Absolute and denatured ethanol are commonly used dehydrating agents in histology and cytology to remove water from tissue specimens. They effectively prepare tissues for embedding or staining while maintaining cellular integrity for accurate microscopic evaluation.","brand":"eam","brandName":"EAM","brandLogo":"/asset/logo/EAM.png"},
	{"id":8,"name":"Isopropyl Alcohol","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/transparent/isopropyl-alcohol.webp","description":"Isopropyl Alcohol is a fast-acting dehydrating agent widely used to remove water from tissue samples during processing. Its reliable performance helps preserve cellular structure, ensuring high-quality results for embedding, staining, and diagnostic analysis.","brand":"eam","brandName":"EAM","brandLogo":"/asset/logo/EAM.png"},
	{"id":9,"name":"Methanol","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/transparent/methanol.webp","description":"Methanol is primarily used as a fixative rather than a dehydrating agent, especially for blood smears and cytological preparations. It rapidly preserves cellular components by preventing autolysis, maintaining detailed morphology for microscopic examination.","brand":"eam","brandName":"EAM","brandLogo":"/asset/logo/EAM.png"},
	{"id":10,"name":"Acetone","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/transparent/acetone.webp","description":"Acetone is a powerful solvent used for rapid dehydration and fixation of tissue samples, particularly in final dehydration stages. Its protein-coagulating properties help preserve cellular structure and prevent degradation for accurate diagnostic analysis.","brand":"eam","brandName":"EAM","brandLogo":"/asset/logo/EAM.png"},
	{"id":11,"name":"Xylene","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/transparent/xylene.webp","description":"Xylene is a key clearing agent in histopathology, used to remove alcohol from tissues and prepare them for paraffin embedding. It ensures optimal penetration of embedding media while maintaining tissue structure for precise microscopic evaluation.","brand":"eam","brandName":"EAM","brandLogo":"/asset/logo/EAM.png"},
	{"id":12,"name":"Xylene Substitute","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/transparent/xylene-substitute.webp","description":"Xylene Substitute provides a safer, low-toxicity alternative to traditional xylene while delivering comparable clearing performance. It effectively removes alcohol during tissue processing while reducing health and environmental risks.","brand":"eam","brandName":"EAM","brandLogo":"/asset/logo/EAM.png"},
	{"id":13,"name":"Zitrus-Clear","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/transparent/zitrus-clear.webp","description":"Zitrus-Clear is a biodegradable, citrus-based clearing agent formulated with D-Limonene as an eco-friendly alternative to xylene. It delivers excellent solvency for deparaffinization and clearing while minimizing toxicity and environmental impact.","brand":"eam","brandName":"EAM","brandLogo":"/asset/logo/EAM.png"},
	{"id":14,"name":"Neutral Buffered Formalin, 10%","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/transparent/neutral-buffered-formalin-10.webp","description":"Natural Buffered Formalin 10% is a ready-to-use primary fixative containing 4% formaldehyde stabilized with methanol and buffered to pH 7.0. It preserves cellular architecture, proteins, and biomolecules, ensuring tissue stability for processing, examination, and long-term archival storage.","brand":"eam","brandName":"EAM","brandLogo":"/asset/logo/EAM.png"},
	{"id":15,"name":"Prefilled Neutral Buffered Formalin, 10%","image":"https://biositeassets.sgp1.cdn.digitaloceanspaces.com/biosite-web/products/Chemicals-Consumables/transparent/prefilled-neutral-buffered-formalin-10.webp","description":"Prefilled Neutral Buffered Formalin 10% is a ready-to-use primary fixative containing 4% formaldehyde stabilized with methanol and buffered to pH 7.0. It preserves cellular architecture, proteins, and other biomolecules, ensuring tissue stability for accurate examination, processing, and long-term archival storage.","brand":"eam","brandName":"EAM","brandLogo":"/asset/logo/EAM.png"},
];

export default function HistopathologyChemicalsConsumables() {
	return <BrandedProductPage category={category} brands={brands} products={products} ctaNoun="histopathology supplies" />;
}
